# Generated by Django 2.2.1 on 2019-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='social_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='VK id'),
        ),
    ]
